/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'muga' at '1/22/15 11:53 PM' with Gradle 2.1
 *
 * @author muga, @date 1/22/15 11:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
